#!/usr/bin/env python3

import os
import sys

from src.utility.arguments import get_arguments
from src.utility.printer import Color, colorprint

def initialize(arguments):
    colorprint(Color.GREEN, 'Initializing environment...')

    # Load virtualenv
    print('Loading virtualenv...', end=' ')
    if os.path.exists(arguments.environment):
        activation_script = os.path.join(os.path.abspath(arguments.environment), 'bin/activate_this.py')
    else:
        colorprint(Color.RED, 'failed\nVirtual environment not found')
        exit(1)

    # Activate virtualenv
    exec(open(activation_script).read(), {'__file__': activation_script})
    colorprint(Color.GREEN, 'done')

if __name__ == '__main__':
    # Parse arguments
    arguments = get_arguments()

    # Initialize and run
    initialize(arguments)
    from src.runner import run
    run(arguments)
